name: Github Actions Pipeline
on:
  push:
    branches: ["test/P01"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  ROLE_TO_ASSUME: arn:aws:iam::415221799955:role/github_worklow_aws
  ECR_APP_REPO: app-repo
  ECR_LOCUST_REPO: locust-repo
  VARIANT_ID: v1
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_name: ${{ secrets.DB_NAME }}
  TF_VAR_jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS
        uses: actions/checkout@v5

      - name: AWS_Credentials_Via_OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{env.ROLE_TO_ASSUME}}

      - name: Login to AWSECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and Push App image in AWSECR
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $REGISTRY/$ECR_APP_REPO:$IMAGE_TAG -t $REGISTRY/$ECR_APP_REPO:latest terraform/applikation/code &&
          docker push $REGISTRY/$ECR_APP_REPO:$IMAGE_TAG &&
          docker push $REGISTRY/$ECR_APP_REPO:latest

      - name: Build and Push Locust image in AWSECR
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $REGISTRY/$ECR_LOCUST_REPO:$IMAGE_TAG -t $REGISTRY/$ECR_LOCUST_REPO:latest terraform/tests/locust &&
          docker push $REGISTRY/$ECR_LOCUST_REPO:$IMAGE_TAG &&
          docker push $REGISTRY/$ECR_LOCUST_REPO:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: Build-and-Push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Credential via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{env.ROLE_TO_ASSUME}}

      - name: Login to aws_ecr
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Setup-Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        env:
          REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="app_image_uri=$REGISTRY/$ECR_APP_REPO:$IMAGE_TAG" \
            -var="locust_image_uri=$REGISTRY/$ECR_LOCUST_REPO:$IMAGE_TAG"

      - name: Umgebungsdetails exportieren
        working-directory: ./terraform
        run: |
          terraform output -json environment_infos > /tmp/environment_infos.json

      - name: Upload environment_infos
        uses: actions/upload-artifact@v4
        with:
          name: environment_infos
          path: /tmp/environment_infos.json
          retention-days: 1

  Locust-Runner-1:
    runs-on: ubuntu-latest
    needs: Deploy
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        env: ["low", "medium", "high", "extreme", "prod"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Credential via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{env.ROLE_TO_ASSUME}}

      - name: Download environment_infos
        uses: actions/download-artifact@v4
        with:
          name: environment_infos
          path: /tmp/infra

      - name: DB migrieren in ${{ matrix.env }}
        run: python3 terraform/tests/benchmark/run_ecs_task.py migrate --env-info /tmp/infra/environment_infos.json --env "${{ matrix.env }}"

      - name: DB leeren in ${{ matrix.env }}
        run: python3 terraform/tests/benchmark/run_ecs_task.py clean --env-info /tmp/infra/environment_infos.json --env "${{ matrix.env }}"

      - name: Locust-Test-1 in ${{ matrix.env }}
        run: python3 terraform/tests/benchmark/run_ecs_task.py run --env-info /tmp/infra/environment_infos.json --env "${{ matrix.env }}" --test "Locust-Test-1"

  Locust-Runner-2:
    runs-on: ubuntu-latest
    needs: Locust-Runner-1
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        env: ["low", "medium", "high", "extreme", "prod"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Credential via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{env.ROLE_TO_ASSUME}}

      - name: Download environment_infos
        uses: actions/download-artifact@v4
        with:
          name: environment_infos
          path: /tmp/infra

      - name: DB migrieren in ${{ matrix.env }}
        run: python3 terraform/tests/benchmark/run_ecs_task.py migrate --env-info /tmp/infra/environment_infos.json --env "${{ matrix.env }}"

      - name: DB leeren in ${{ matrix.env }}
        run: python3 terraform/tests/benchmark/run_ecs_task.py clean --env-info /tmp/infra/environment_infos.json --env "${{ matrix.env }}"

      - name: Locust-Test-2 in ${{ matrix.env }}
        run: python3 terraform/tests/benchmark/run_ecs_task.py run --env-info /tmp/infra/environment_infos.json --env "${{ matrix.env }}" --test "Locust-Test-2"

  # Teardown (auskommentiert: Ressourcen bleiben stehen, um testzeiten zu verkürzen)
  # Teardown:
  #   runs-on: ubuntu-latest
  #   needs: Locust-Runner-2
  #   if: always()
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #
  #     - name: AWS Credential via OIDC
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-region: ${{env.AWS_REGION}}
  #         role-to-assume: ${{env.ROLE_TO_ASSUME}}
  #
  #     - name: Setup-Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: 1.5.0
  #
  #     - name: Terraform Destroy
  #       working-directory: ./terraform
  #       run: |
  #         terraform init
  #         terraform destroy -auto-approve \
  #           -var="app_image_uri=unused" \
  #           -var="locust_image_uri=unused"
